Item Model and Controller
thabaniBBD2712/Food-Delivery-API pull request #8
Opened 2023-04-16 14:15 UTC by hewitt-BBD

- Created the Item model which contains its information, status and category (these had to be JOINed)
- Created a view [ItemView] to JOIN the Item, ItemInformation, ItemStatus and ItemCategory tables
- Created the following HTTP request 
    - /Item -> Lists all the items
    - /Item/Restaurant/{id} -> Lists all items from a restaurant
    - /Item/{id} -> Gets item by ID
    - /Item/Persist/{Item} -> Inserts/ Updates an Item

-- I still need to add a delete function though

2023-04-17 16:54 UTC, willacharlotte requested changes
* Add PUT and DELETE methods
* Review endpoint name in POST method

2023-04-19 07:46 UTC, hewitt-BBD commented
I've added the required methods. Please have a look. I just have a concern about the information table as i was implicitly adding that info when posting the item...

2023-04-19 11:43 UTC, ZeerakBaig-BBD approved these changes

2023-04-19 11:44 UTC, willacharlotte approved these changes

2023-04-19 11:44 UTC, merged